import type { CockpitStateSnapshot } from '@/types/cockpit';

const now = new Date().toISOString();

export const sampleSnapshot: CockpitStateSnapshot = {
  settings: {
    assignees: ['Combo', 'Codex', 'Claude'],
    projectTemplate: {
      name: '新产品研发项目',
      oneLiner: '一句话说明这个项目要达成什么',
      owner: 'Combo',
      members: ['Combo'],
      weeklyFocus: ['明确目标', '拆出第一批任务'],
      summary: '这个项目还在整理中。',
      status: 'active',
      stage: 'exploring',
      priority: 'medium',
    },
    taskDefaults: {
      owner: '',
      status: 'todo',
      priority: 'medium',
      dueDateOffsetDays: 0,
    },
    workspace: {
      defaultTaskFilter: 'active',
      contextLimit: 6,
      decisionLimit: 3,
    },
  },
  selectedProjectId: 'project-cockpit',
  projects: [
    {
      id: 'project-cockpit',
      name: 'AI Project Cockpit',
      oneLiner: '为产品研发小队设计的自用 AI-native 项目驾驶舱',
      description: '第一版聚焦项目状态、任务、上下文、AI 工作记录和关键决策的卡片化沉淀。',
      status: 'active',
      stage: 'planning',
      owner: 'Combo',
      members: ['Combo', 'Codex'],
      priority: 'high',
      weeklyFocus: ['明确 MVP 边界', '搭建可运行原型', '验证卡片式项目驾驶舱手感'],
      summary: '方向已收敛到纯自用产品研发工具。当前重点是基于 team-cards 复用卡片交互，并用 SQLite 保存本地数据。',
      createdAt: now,
      updatedAt: now,
    },
  ],
  outlineStageGoals: [
    {
      id: 'outline-goal-planning',
      projectId: 'project-cockpit',
      stage: 'planning',
      goal: '明确 MVP 的信息架构和主工作流',
      createdAt: now,
      updatedAt: now,
    },
  ],
  outlineItems: [
    {
      id: 'outline-mvp',
      projectId: 'project-cockpit',
      stage: 'planning',
      task: '把项目状态、任务、上下文、AI Record 和决策组织成可长期维护的驾驶舱',
      status: 'doing',
      note: '先验证自用手感，不做 SaaS 化。',
      order: 0,
      createdAt: now,
      updatedAt: now,
    },
  ],
  tasks: [
    {
      id: 'task-ia',
      projectId: 'project-cockpit',
      title: '确定第一版信息架构',
      description: '左侧项目列表，右侧驾驶舱，任务、上下文、AI Record 和决策全部使用卡片。',
      status: 'doing',
      owner: 'Combo',
      priority: 'high',
      dueDate: '',
      subtasks: [
        { id: 'sub-1', title: '确认项目入口形态', completed: true },
        { id: 'sub-2', title: '确认数据保存方式', completed: true },
      ],
      notes: '已决定使用 SQLite，不做登录，不接飞书。',
      source: 'manual',
      createdAt: now,
      updatedAt: now,
    },
  ],
  contexts: [
    {
      id: 'context-prd',
      projectId: 'project-cockpit',
      title: '初始 PRD',
      type: 'doc',
      content: '原始 PRD 已放在 docs/ai_project_cockpit_prd.md，作为后续讨论和迭代的基础。',
      url: '',
      source: 'docs',
      importance: 'high',
      pinned: true,
      archived: false,
      workspaceVisible: true,
      createdAt: now,
      updatedAt: now,
    },
  ],
  aiRecords: [
    {
      id: 'ai-record-decisions',
      projectId: 'project-cockpit',
      title: '方向收敛记录',
      tool: 'Codex',
      inputSummary: '基于 PRD 讨论第一版需要先确定的问题。',
      outputSummary: '第一版定位为纯自用产品研发项目驾驶舱，AI 是辅助模块，Context 和 Task 都用卡片。',
      rawOutput: '',
      value: 'decision_support',
      status: 'used',
      createdAt: now,
      updatedAt: now,
    },
  ],
  finances: [
    {
      id: 'finance-server',
      projectId: 'project-cockpit',
      title: '云服务器月租',
      amount: 298,
      category: 'service',
      status: 'approved',
      date: new Date().toISOString().slice(0, 7) + '-01',
      description: '火山云服务器月度费用，用于部署 Cockpit 及其他项目。',
      receipts: [],
      payer: 'Combo',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'finance-domain',
      projectId: null,
      title: '域名续费',
      amount: 69,
      category: 'service',
      status: 'reimbursed',
      date: new Date().toISOString().slice(0, 7) + '-03',
      description: '团队通用域名年度续费。',
      receipts: [],
      payer: 'Combo',
      createdAt: now,
      updatedAt: now,
    },
    {
      id: 'finance-vscode',
      projectId: null,
      title: 'VS Code 扩展订阅',
      amount: 35,
      category: 'service',
      status: 'pending',
      date: new Date().toISOString().slice(0, 7) + '-05',
      description: 'Copilot 月度订阅。',
      receipts: [],
      payer: 'Combo',
      createdAt: now,
      updatedAt: now,
    },
  ],
  testIssues: [
    {
      id: 'test-issue-project-filter',
      projectId: 'project-cockpit',
      title: '财务面板需要按项目筛选',
      description: '测试时发现财务记录虽然能关联项目，但财务列表没有项目筛选入口。',
      reporter: 'Combo',
      severity: 'medium',
      status: 'triaging',
      attachments: [],
      archived: false,
      createdAt: now,
      updatedAt: now,
    },
  ],
  decisions: [
    {
      id: 'decision-scope',
      projectId: 'project-cockpit',
      title: '第一版只做纯自用产品研发工具',
      decision: '不做登录、租户、SaaS 化权限、飞书集成和复杂工作流。',
      rationale: '先获得真实日常使用手感，避免过早抽象。',
      alternatives: '未来 SaaS 雏形；接入飞书；以 AI Chat 为主入口。',
      impact: '技术方案可以先采用本地 SQLite，产品页面优先围绕项目状态和卡片沉淀展开。',
      decidedBy: ['Combo'],
      pinned: true,
      archived: false,
      workspaceVisible: true,
      createdAt: now,
      updatedAt: now,
    },
  ],
};
